### ISSUE TITLE
Not working on latest Rocksmith update

### ISSUE THREAD

**Issue by Wildenhaus** [hunterpankey/RockSnifferGui#4]
**Describe the bug**
It seems that this year's random update that broke CDLC also broke this app.

**To Reproduce**
Try running the GUI with the latest version of Rocksmith 2014. It sees the game is running but doesn't pull data.

**Expected behavior**
For it to pull data from the game.

**Desktop (please complete the following information):**
Windows 10

```
[2/11/2023 6:39:25 PM] GameProcessWatcher: Shutting down game process watcher worker thread.
[2/11/2023 6:39:25 PM] Error while reading memory: System.InvalidOperationException No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at RockSnifferLib.RSHelpers.RSMemoryReader.FollowPointers(Int32 entryAddress, Int32[] offsets) in D:\source\personal\github\RockSniffer\RockSnifferLib\RSHelpers\RSMemoryReader.cs:line 139
   at RockSnifferLib.RSHelpers.RSMemoryReader.DoReadout() in D:\source\personal\github\RockSniffer\RockSnifferLib\RSHelpers\RSMemoryReader.cs:line 47
   at RockSnifferLib.Sniffing.Sniffer.<DoMemoryReadout>d__33.MoveNext() in D:\source\personal\github\RockSniffer\RockSnifferLib\Sniffing\Sniffer.cs:line 181
```

**Comment by Wildenhaus** [comment]
I was able to fix this with a few steps.

- Updated the csproj to .NET 6 with the [update assistant](https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant)
- Updated the nuget packages (sqlite 1.0.113 is no longer available)
- Added the latest RockSnifferLib and Rocksmith2014PsarcLib to the solution
- In RockSnifferLib's `Sniffer.cs` I changed the following because it would not properly trigger the start of a song (it was expecting state to go from In Menu -> Song Starting, when it should expect In Menu -> Song Selected -> Song Starting):

```
private void Sniffer_OnStateChanged( object sender, OnStateChangedArgs e )
{
  var newState = e.newState;
  var oldState = e.oldState;

  if ( ( oldState == SnifferState.IN_MENUS || oldState == SnifferState.SONG_SELECTED ) &&
      newState == SnifferState.SONG_STARTING )
  {
    OnSongStarted?.Invoke( this, new OnSongStartedArgs { song = currentCDLCDetails } );
  }
  else if ( newState == SnifferState.IN_MENUS &&
      oldState != SnifferState.NONE )
  {
    OnSongEnded?.Invoke( this, new OnSongEndedArgs { song = currentCDLCDetails } );
  }
}

```

**Comment by apelliciari** [comment]
@Wildenhaus can you release it as an .exe? thanks

**Comment by Kinc4id** [comment]
Would love to see an update here as well.
